// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urhqstatsbrldywgrqpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaHFzdGF0c2JybGR5d2dycXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDc5NjcsImV4cCI6MjA2NjYyMzk2N30.DGx-9MR7zT--H4VWivqYV_VWODy16jA4cGG188Rq13k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);